# Generated by Django 3.2.8 on 2021-12-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_audit', '0002_auto_20211026_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='http_referer',
            field=models.TextField(verbose_name='HTTP Referer'),
        ),
    ]
