# Generated by Django 3.2.8 on 2021-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_audit', '0003_alter_auditlog_http_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='response_body',
            field=models.JSONField(default=dict),
        ),
    ]
